name: joshrhoades
favicon: null
layout_spectrum: 0.73398
typography_spectrum: 0.5332975
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfdebf'
    - '#594c46'
    - '#828081'
    - '#f7763d'
    - '#ffad61'
  brandStrength: 0.5941665
  lightness: 0
  saturation: 0.4668843
  rhythmicContrast: 0.25
purpose: []
