favicon: null
name: joshrhoades
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4668843
  brandStrength: 0.5941665
  lightness: 0
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  rhythmicContrast: 0.8920515
typography_spectrum: 0.5332975
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.73398
analytics:
  twitter: null
  google: null
  facebook: null
