layout_spectrum: 0.5912997
color:
  saturation: 0.8480129
  brandStrength: 0.5941665
  lightness: 0.217508
  rhythmicContrast: 0.8920515
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.5332975
name: joshrhoades
